repos:
-   repo: https://github.com/cesar-rodriguez/terrascan
    rev: v0.2.0
    hooks:
    -   id: terrascan
        pass_filenames: false
        args: [-l=infra] #NOTE: that this is the directory you created earlier to host your terraform
        verbose: true
